export TARGETCC = $(strip $(CC))
export TARGETLD = $(strip $(LD))
export TARGETAR = $(strip $(AR))

export PYTHON=python3

export PKG_CONFIG_LIBDIR=

override MAKEFLAGS=""

.PHONY: all

all:
	$(MAKE) -C $(SOLETTA_BASE_DIR) CFLAGS="$(SOLETTA_CFLAGS)" LDFLAGS="$(SOLETTA_LDFLAGS)" alldefconfig
	(cd $(SOLETTA_BASE_DIR); tools/kconfig/merge_config.sh .config $(SOLETTA_CONF))
	$(MAKE) -C $(SOLETTA_BASE_DIR) CFLAGS="$(SOLETTA_CFLAGS)" LDFLAGS="$(SOLETTA_LDFLAGS)"
