MDEF_FILE = prj.mdef
KERNEL_TYPE = $(KERNEL)
BOARD ?= arduino_101
CONF_FILE ?= prj.conf

KBUILD_ZEPHYR_APP = libjerry-core.a

obj-y += src/

export KBUILD_ZEPHYR_APP BOARD

include ${ZEPHYR_BASE}/Makefile.inc

ifeq ($(CONFIG_NETWORKING_WITH_BT), y)
	QEMU_EXTRA_FLAGS = -serial unix:/tmp/bt-server-bredr
else
	include $(ZEPHYR_BASE)/samples/net/common/Makefile.ipstack
endif
