# Copyright (c) 2017, Intel Corporation.

JERRY_BASE ?= $(ZJS_BASE)/deps/jerryscript

ccflags-y += -Wall -Werror

# Select extended ANSI C/POSIX function set in recent Newlib versions
ccflags-y += -D_XOPEN_SOURCE=700

ccflags-y += -I$(ZJS_BASE)/src
ccflags-y += -I$(JERRY_BASE)/jerry-core

obj-$(ZJS_SENSOR_ACCEL) += zjs_sensor_accel.o
obj-$(ZJS_SENSOR_GYRO) += zjs_sensor_gyro.o
obj-$(ZJS_SENSOR_LIGHT) += zjs_sensor_light.o
obj-$(ZJS_SENSOR_TEMP) += zjs_sensor_temp.o
