#!/usr/bin/env python3

import os
import sys
import json
import re
import shutil
import pprint

featurefile = ''

args = {}

for i in sys.argv[1:]:
    option, value = i.split('=')[:2]
    args[option] = value

if 'SCRIPT' not in args:
    print("Generating modules header")
else:
    print("Analyzing %s for %s" % (args['SCRIPT'], args['BOARD']))

json_tree = {}

deps_list = []
zconf = []
zjs_conf = []
jrs_conf = []
lsrc = []
js_modules = []

def do_print(s):
    if 'V' in args and args['V'] == '1':
        p = pprint.PrettyPrinter(indent=1)
        p.pprint(s)

def merge_lists(l1, l2):
    if l1 != None:
            for i in l2:
                if i not in l1:
                    l1.append(i)

def parse_list(tree, list=[]):
    for file in list:
        if file.endswith(".json"):
            do_print("opening " + file)
            with open("src/" + file) as f:
                data = json.load(f)
            if 'targets' in data:
                if args['BOARD'] not in data['targets']:
                    continue;
            # Index the entry by the require name, if exists
            if 'require' in data:
                # if the require name exists, index by module
                # this is done due to some targets needing a restricted set of
                # .json files (ARC). When this subset of files is looked at
                # against the JS file, the require's still need to be parsed
                # correctly so we have to add a second entry in the tree that
                # is specific to this target (ARC).
                if data['require'] in tree:
                    tree[data['module']] = data
                else:
                    tree[data['require']] = data
            # else index by the module name
            elif 'module' in data:
                tree[data['module']] = data
            else:
                print("Error: JSON entry %s must have either 'module' or 'require'" % file)

def build_tree(tree, restrict):
    if restrict != []:
        parse_list(tree, list=restrict)
    else:
        parse_list(tree, list=os.listdir("src/"))

def get_dep_list_helper(dlist, dep, board, tree):
    if dep in tree:
        entry = tree[dep]
        if 'targets' in entry:
            if args['BOARD'] not in entry.get('targets', []):
                return
        if 'depends' in entry:
            merge_lists(dlist, entry['depends'])
            for i in entry['depends']:
                get_dep_list_helper(dlist, i, board, tree)

def get_dep_list(dlist, board, tree):
    for dep in tree:
        if 'targets' not in tree[dep]:
            merge_lists(dlist, [dep])
        get_dep_list_helper(dlist, dep, board, tree)

def gather_deps_helper(js, dep, dlist, zlist, zjslist, jrslist, srclist, tree):
    if dep in tree:
        entry = tree[dep]
        if 'targets' in entry:
            if args['BOARD'] not in entry.get('targets', []):
                return
        for i in entry.get('depends', []):
            do_print("gathering dependencies for " + i)
            if i not in dlist:
                dlist.append(i)
            gather_deps_helper(js, i, dlist, zlist, zjslist, jrslist, srclist, tree)
        if 'src' in entry:
            src = entry['src']
            if isinstance(src, list):
                merge_lists(srclist, src)
            else:
                if 'common' in src:
                    merge_lists(srclist, src['common'])
                for key, value in src.items():
                    if key != "common":
                        # var x = require(module).key
                        off_req = re.search(r"var .*require\([\'\"]%s[\"\']\)\.%s" % (entry['require'], key), js)
                        if off_req:
                            if 'src' in value:
                                merge_lists(srclist, value['src'])
                            if 'zjs_config' in value:
                                merge_lists(zjslist, value['zjs_config'])
                        else:
                            # var x = require(module)
                            # var y = x.y
                            match_name = re.search(r"var .*require\([\'\"]%s[\"\']\)" % entry['require'], js)
                            var_name = match_name.group(0).split(' ')[1]
                            match_use = re.search(r"%s\.%s" % (var_name, key), js)
                            if match_use:
                                if 'src' in value:
                                    merge_lists(srclist, value['src'])
                                if 'zjs_config' in value:
                                    merge_lists(zjslist, value['zjs_config'])
        if 'zephyr_conf' in entry:
            z_conf = entry['zephyr_conf']
            if 'all' in z_conf:
                merge_lists(zlist, z_conf['all'])
            if args['BOARD'] in z_conf:
                merge_lists(zlist, z_conf[args['BOARD']])
        if 'jrs_config' in entry:
            merge_lists(jrslist, entry['jrs_config'])
        if 'zjs_config' in entry:
            merge_lists(zjslist, entry['zjs_config'])

def gather_deps(file, dlist, zlist, zjslist, jrslist, srclist, tree, force=[]):
    with open(file) as js:
        text = js.read()

    if force != []:
        for f in force:
            with open("src/" + f) as file:
                data = json.load(file)
                gather_deps_helper(text, data['module'], dlist, zlist, zjslist, jrslist, srclist, tree)
    else:
        for i in tree:
            if 'require' in tree[i]:
                if re.search(r"require\([\'\"]%s[\"\']\)" % tree[i]['require'], text):
                    if i not in dlist:
                        dlist.append(i)
                    gather_deps_helper(text, i, dlist, zlist, zjslist, jrslist, srclist, tree)
            elif 'constructor' in tree[i]:
                if re.search(r"%s\(.*" % tree[i]['constructor'], text):
                    if i not in dlist:
                        dlist.append(i)
                    gather_deps_helper(text, i, dlist, zlist, zjslist, jrslist, srclist, tree)
            if 'object' in tree[i]:
                if re.search(r"%s\." % tree[i]['object'], text):
                    merge_lists(zjslist, tree[i]['zjs_config'])
                    merge_lists(srclist, tree[i]['src'])
                    dlist.append(tree[i]['object'])

    # Get any deps for the board
    gather_deps_helper(text, args['BOARD'], dlist, zlist, zjslist, jrslist, srclist, tree)

def write_jrsconfig(list):
    if 'PROFILE' in args:
        if os.path.exists(args['PROFILE']):
            shutil.copyfile(args['PROFILE'], args['PROFILE'] + '.bak')
        with open("fragments/jerry_feature.base", "r") as jrs:
            feature = jrs.read()
        with open(args['PROFILE'], "w") as p:
            for i in list:
                feature = feature.replace(i, "#" + i)
            p.write(feature)

def write_makefile(src, zconf, file):
    with open(args['MAKEBASE'], "r") as b:
        base = b.read()
    with open(file, "w") as f:
        f.write(base)
        if src:
            f.write("obj-y += \\\n")
            for i in src:
                f.write("\t" + i.replace(".c", ".o") + " \\\n")
            f.write("\nccflags-y += \\\n")
            for i in zconf:
                f.write("\t" + i + " \\\n")
            f.write("\n")

def write_zconf(list, file):
    with open(file, "w") as f:
        for i in list:
            f.write(i + '\n')

def write_modules(list, tree):
    headers = []
    inits = {}
    gbl_inits = {}
    with open('outdir/include/zjs_modules_gen.h', 'w') as file:
        for i in list:
            entry = tree.get(i, None)
            if entry:
                if 'init' in entry:
                    inits[i] = {}
                    inits[i]["inits"] = entry['init']
                if 'cleanup' in entry:
                    inits[i]["cleanups"] = entry['cleanup']
                if 'header' in entry:
                    merge_lists(headers, entry['header'])
                if 'global_init' in entry:
                    gbl_inits[i] = {}
                    gbl_inits[i]["inits"] = entry['global_init']
                if 'global_cleanup' in entry:
                    gbl_inits[i]["cleanups"] = entry['global_cleanup']
        # Add include headers
        file.write("// This is a generated file\n")
        file.write("// Includes:\n")
        file.write("#include \"jerryscript.h\"\n")
        for i in headers:
            file.write("#include \"%s\"\n" % i)
        file.write("""typedef jerry_value_t (*initcb_t)();
typedef void (*cleanupcb_t)();
typedef struct module {
    const char *name;
    initcb_t init;
    cleanupcb_t cleanup;
    jerry_value_t instance;
} module_t;
typedef struct gbl_module {
    const char *name;
    void (*init)();
    void (*cleanup)();
} gbl_module_t;
module_t zjs_modules_array[] = {\n""")
        for i in inits:
            file.write("    {\"%s\", %s" % (i, inits[i]["inits"][0]))
            if 'cleanups' in inits[i]:
                file.write(", %s" % inits[i]["cleanups"][0])
            file.write("},\n")
        file.write("};\n")
        file.write("gbl_module_t zjs_global_array[] = {\n")
        for i in gbl_inits:
            file.write("    {\"%s\", %s" % (i, gbl_inits[i]["inits"][0]))
            if 'cleanups' in gbl_inits[i]:
                file.write(", %s" % gbl_inits[i]["cleanups"][0])
            file.write("},\n")
        file.write("};\n")

if args['BOARD'] == 'linux':
    restrict = args['RESTRICT'].split(',')
    restrict = [i.strip() for i in restrict]
    build_tree(json_tree, restrict)
    do_print(json_tree)
    all_list = []
    get_dep_list(all_list, args['BOARD'], json_tree)
    for i in all_list:
        print("Using module: " + i)
    write_modules(all_list, json_tree)
else:
    if 'JS' in args:
        with open(args['SCRIPT'], 'r') as s:
            js = s.read()
        with open(args['JS'], 'w') as f:
            for i in os.listdir("modules/"):
                if re.search(r"require\([\'\"]%s[\"\']\)" % i, js):
                    js_modules += [i]
            for i in js_modules:
                with open('modules/' + i) as mod:
                    f.write(mod.read())
                    f.write("\n")
            f.write(js)
        js_file = args['JS']
    else:
        js_file = args['SCRIPT']

    restrict = args.get('RESTRICT', '')
    if restrict != '':
        restrict = restrict.split(',')
        restrict = [i.strip() for i in restrict]
        do_print("Only using modules: " + str(restrict))
    else:
        restrict = []

    force = args.get('FORCE', '')
    if force != '':
        force = force.split(',')
        do_print("Forcing inclusion of: " + str(force))
    else:
        force = []

    build_tree(json_tree, restrict)
    do_print(json_tree)
    gather_deps(js_file, deps_list, zconf, zjs_conf, jrs_conf, lsrc, json_tree, force=force)
    for i in deps_list:
        print("Using module: " + i)

    write_zconf(zconf, args['PRJCONF'])
    write_makefile(lsrc, zjs_conf, args['MAKEFILE'])
    write_jrsconfig(jrs_conf)

    if args['BOARD'] != 'arc':
        write_modules(deps_list, json_tree)
