#!/bin/bash

# Copyright (c) 2016, Intel Corporation.
# Author: Geoff Gustafson <geoff@linux.intel.com>

# blflash - flash the bootloader in deps/a101fw

FWDIR=$ZJS_BASE/deps/a101fw

echo
echo blflash: Flashing new bootloader...
cd $FWDIR/arduino101_flashpack
./flash_dfu.sh -b
cd -

echo
echo blflash: You may now flash new Zephyr images to the X86 and ARC partitions.
echo Don\'t forget you need Zephyr to expect the new size, too!
