#!/bin/bash

# Copyright (c) 2016, Intel Corporation.
# Author: Geoff Gustafson <geoff@linux.intel.com>

# trlite - a local version of the tests we run in Travis
#   trlite [-v] [vmname] [testnum]
#
#   -v turns on verbose output
#   by default, runs all tests
#   trlite 1 or trlite zephyr runs just VM #1 "zephyr" tests
#   trlite 2 or trlite linux  runs just VM #2 "linux"  tests
#   trlite 3 or trlite ashell runs just VM #3 "ashell" tests
#   optional testnum is the first subtest to start with (default 1)

if [ ! -d "$ZJS_BASE" ]; then
   >&2 echo "ZJS_BASE not defined. You need to source zjs-env.sh."
   exit 1
fi

TRLDIR=$ZJS_BASE/.trlite
TRLPATCH=$TRLDIR/patch

if [ "$1" == "-h" -o "$1" == "-?" ]; then
    echo usage: trlite [-h] [-v] [vmname] [testnum]
    echo
    echo positional arguments:
    echo "  vmname   vm number 1/2/3 or name zephyr/linux/ashell (default: all)"
    echo "  testnum  subtest to start with (default: 1)"
    echo
    echo optional arguments:
    echo "  -h, -?   show this help message and exit"
    echo "  -v       turn on verbose build output"
    exit 1
fi

VERBOSE=
if [ "$1" == "-v" ]; then
    VERBOSE=V=1
    shift
fi

# flags for running tests from the different VMs
VM1=y
VM2=y
VM3=y

if [ "$1" == "1" -o "$1" == "zephyr" ]; then VM2=n; VM3=n; shift; fi
if [ "$1" == "2" -o "$1" == "linux" ]; then VM1=n; VM3=n; shift; fi
if [ "$1" == "3" -o "$1" == "ashell" ]; then VM1=n; VM2=n; shift; fi

START=1
if [[ "$1" =~ ^[0-9]+$ ]]; then
    START=$1
    shift
fi

rm -rf $TRLDIR

echo Building ZJS tree: "$ZJS_BASE"
echo Cloning git tree...
git clone -l $ZJS_BASE $TRLDIR > /dev/null 2>&1

echo Cloning git submodules...
cd $TRLDIR/deps
for i in */; do
    git clone -l ../../deps/$i/.git $i > /dev/null 2>&1
done

echo Preserving uncommitted changes:
cd $ZJS_BASE
git diff --cached --stat
git diff --cached > $TRLPATCH
cd $TRLDIR
patch -p1 < patch > /dev/null

# pause to allow consideration of diffs being applied
sleep 3

echo Updating submodules...
make update

echo
echo Running tests...

source zjs-env.sh
source deps/zephyr/zephyr-env.sh

# requires: first arg is a <=10-char label, second arg is command
#  effects: runs banner with label, then runs the command; if it fails, prints
#             label on the command line before exiting
function try_command()
{
    TESTNUM=$((TESTNUM + 1))
    if [ "$TESTNUM" -lt "$START" ]; then
        echo "Skipping test #$TESTNUM"
        return
    fi

    LABEL=$1
    shift
    banner "$LABEL"
    if ! $*; then
        echo Error: Failed in $1!
        exit $?
    fi
    echo Success: $LABEL
}

#
# Tests from VM #1
#

if [ "$VM1" == "y" ]; then
    TESTNUM=0

    # A101 build tests spanning all modules
    try_command "helloworld" make $VERBOSE
    try_command "traffic" make $VERBOSE JS=samples/TrafficLight.js
    try_command "pwm" make $VERBOSE JS=samples/PWM.js
    try_command "i2c" make $VERBOSE JS=samples/I2C.js
    try_command "uart" make $VERBOSE JS=samples/UART.js
    try_command "events" make $VERBOSE JS=samples/tests/Events.js
    try_command "perf" make $VERBOSE JS=tests/test-performance.js

    # k64f build tests
    git clean -dfx
    try_command "k64f hello" make $VERBOSE BOARD=frdm_k64f

    # arc build tests
    git clean -dfx
    try_command "arc" make $VERBOSE arc

    # 256KB partition build tests
    git clean -dfx
    source zjs-env.sh 256
    try_command "btgrove" make $VERBOSE JS=samples/WebBluetoothGroveLcdDemo.js
fi

#
# Tests from VM #2
#

if [ "$VM2" == "y" ]; then
    TESTNUM=0

    # git check
    try_command "git check" git diff --check $(git rev-list HEAD | tail -1)

    # linux build tests
    try_command "linux" make $VERBOSE linux

    # linux unit tests
    try_command "unit tests" ./outdir/linux/release/jslinux --unittest
fi

#
# Tests from VM #3
#

if [ "$VM3" == "y" ]; then
    TESTNUM=0

    # ashell tests
    git clean -dfx
    try_command "ashell" make $VERBOSE DEV=ashell
fi

# clean up on success
cd $ZJS_BASE
rm -rf $TRLDIR
