#!/usr/bin/python3

# Copyright (c) 2017, Intel Corporation.

# zjsbanner - prints input text in large format

import sys

alphabet = ['4avhh', 'uhuhu', 'fgggf', 'uhhhu', 'vgugv', 'vgugg', 'fgjhe',
            'hhvhh', 'v444v', 'v22ic', 'hisih', 'ggggv', 'hrlhh',
            'hpljh', 'ehhhe', 'uhugg', 'ehhjf', 'uhuih', 'fge1u', 'v4444',
            'hhhhe', 'hhha4', 'hhlrh', 'ha4ah', 'ha444', 'v248v']

digits = ['ejlpe', '4c44v', 'u116v', 'u1e1u', 'hhv11',
          'vgu1u', 'fguhe', 'v248g', 'ehehe', 'ehf11']

other = {
    ' ': '00000',
    '?': 'e1c04',
    '.': '00004',
    '-': '00e00',
    '_': '0000v',
}

def find_pattern(char, line):
    # returns: five character string
    if char.isalpha():
        char = char.upper()
        index = ord(char) - ord('A')
        ptnchr = alphabet[index][line]
    elif char.isdigit():
        index = ord(char) - ord('0')
        ptnchr = digits[index][line]
    else:
        if char not in other:
            char = '?'
        ptnchr = other.get(char)[line]

    if ptnchr.isalpha():
        mask = ord(ptnchr) - ord('a') + 10
    else:
        mask = ord(ptnchr) - ord('0')

    return "{0:5b}".format(mask).replace('1', '#').replace('0', ' ')

def banner(message):
    while len(message) > 0:
        print("")
        line = message[:11]
        message = message[11:]

        for i in range(5):
            out = ''
            for j in range(len(line)):
                out += (find_pattern(line[j], i) + '  ')
            print(out)

def main():
    if len(sys.argv) <= 1:
        print("usage: zjsbanner <text>")
        sys.exit(1)

    banner(' '.join(sys.argv[1:]))

if __name__ == "__main__":
   main()
