ccflags-y += -I$(JERRY_BASE)/jerry-core
ccflags-y += -I$(ZEPHYR_BASE)/drivers

obj-y += main.o \
         zjs_aio.o \
         zjs_ble.o \
         zjs_buffer.o \
         zjs_gpio.o \
         zjs_ipm.o \
         zjs_modules.o \
         zjs_pwm.o \
         zjs_timers.o \
         zjs_util.o
